.PHONY: clean All

All:
	@echo "----------Building project:[ task_Three - Debug ]----------"
	@cd "task_Three" && "$(MAKE)" -f  "task_Three.mk"
clean:
	@echo "----------Cleaning project:[ task_Three - Debug ]----------"
	@cd "task_Three" && "$(MAKE)" -f  "task_Three.mk" clean
